all:
	cp logitech.service ${HOME}/.config/systemd/user/
	mkdir -p ${HOME}/Documents/Random/Logitech/
	chmod u+x Lighting.sh
	cp Lighting.sh ${HOME}/Documents/Random/Logitech/

clean:
	rm ${HOME}/.config/systemd/user/logitech.service
	rm ${HOME}/Documents/Random/Logitech/Lighting.sh
